# Site settings
title: Logan Brock
email: LLBrock@uncg.edu
description: >
  Logan Brock: Academic Librarian Website.
  A portfolio site created by a graduate student studying Library and Information Science.
baseurl: ""
url: ""

# User setting
owner: Logan Brock
github_username: leanderbrock14
address:
  - line:
  - line:
telephone:
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown