# Site settings
title:Logan Brock
email:LLBrock@uncg.edu
description: > # this means to ignore newlines until "baseurl:"
  A portfolio site created by a Graduate student studying Library and Information Science.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner:Logan Brock
email:LLBrock@uncg.edu
github_username:
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown